# Site settings
# These are used to personalize your new site.
title: Trevor Abel # your name here
logo: "/images/0.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cyber Security (class of 2021)
  <br /><br />
  <a href="file:TrevorAbelResume.docx">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/trevor-abel-87a5b1154/">View My LinkedIn Profile</a>
repository: "trevorabel/trevorabel.github.io"
github_username:  trevorabel # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

